data:
  apply_whitening: true
  bandpass:
    high: 1024.0
    low: 20.0
  downsample_target_t: 1024
  mlgwsc_files:
    train_background: train_background_gen48h_01.hdf
    train_foreground: train_foreground_gen48h_01.hdf
    train_injections: train_injections_gen48h_01.hdf
    val_background: val_background_gen48h_01.hdf
    val_foreground: val_foreground_gen48h_01.hdf
    val_injections: val_injections_gen48h_01.hdf
  overlap: 0.9
  quality_threshold: 0.7
  sample_rate: 4096
  segment_length: 4.0
  test_split: 0.15
  train_split: 0.7
  val_split: 0.15
development:
  debug_mode: false
  quick_epochs: 5
  quick_mode: false
  quick_samples: 100
  run_integration_tests: false
  run_unit_tests: false
  save_intermediate_outputs: false
  test_data_fraction: 0.1
  verbose_logging: false
evaluation:
  compute_classification_report: true
  compute_confusion_matrix: true
  compute_pr_auc: true
  compute_roc_auc: true
  optimal_threshold_method: youden
  plot_dpi: 300
  plot_format: png
  save_plots: true
  threshold_range:
  - 0.1
  - 0.9
  threshold_steps: 50
inference:
  batch_size: 32
  confidence_threshold: 0.5
  include_ranking_statistics: true
  include_timestamps: true
  mlgwsc_format: true
  output_format: hdf5
  real_time_mode: false
  save_predictions: true
  save_spike_patterns: false
lhc_optimizations:
  applied: true
  expected_improvements:
    binary_latent_configs: 1048576
    computational_speedup: 6.4x
    projected_accuracy_gain: 29.9%
    threshold_selectivity: 2.2x
  optimizations:
  - time_steps_reduced_32_to_5
  - threshold_increased_0.55_to_1.2
  - beta_decay_optimized_to_0.9
  - architecture_simplified
  - learning_rate_increased_to_0.001
  - cpc_parameters_optimized
  paper_reference: Dillon et al. arXiv:2508.00063v1 [hep-ph] 31 Jul 2025
logging:
  backup_count: 3
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_file: cpc_snn_gw.log
  log_to_file: true
  max_log_size_mb: 100
  tensorboard:
    log_dir: ./tensorboard_logs
    update_freq: epoch
  wandb:
    entity: null
    notes: CPC+SNN neuromorphic GW detection
    project: cpc-snn-gw
    tags:
    - neuromorphic
    - gravitational-waves
model:
  bridge:
    encoding_type: learnable_multi_threshold
    gradient_scaling: 1.0
    latency_coding: false
    normalization_method: layer_norm
    num_threshold_levels: 8
    rate_coding_window: 16
    spike_regularization: 0.005
    temporal_encoding: true
  cpc:
    dropout_rate: 0.1
    hidden_dim: 512
    latent_dim: 256
    num_layers: 3
    use_layer_norm: true
  snn:
    adaptive_threshold: true
    beta: 0.9
    hidden_sizes:
    - 64
    - 32
    membrane_reset: subtract
    num_classes: 2
    spike_regularization_target: 0.15
    surrogate_beta: 4.0
    surrogate_gradient: hard_sigmoid
    tau_mem: 15.0
    tau_syn: 8.0
    threshold: 0.8  # ✅ LHC FIX: Moderate threshold (1.2 za wysokie dla GW)
    time_steps: 5
profiling:
  batch_sizes:
  - 1
  - 4
  - 8
  - 16
  - 32
  enabled: false
  memory_alert_threshold: 0.9
  num_benchmark_runs: 100
  num_warmup_runs: 10
  target_inference_ms: 100
  track_memory: true
system:
  cache_dir: ./cache
  checkpoint_dir: ./checkpoints
  data_dir: /teamspace/studios/this_studio/data/dataset-4/gen48h_01
  device: auto
  log_level: INFO
  memory_fraction: 0.8
  output_dir: ./outputs
  use_mixed_precision: true
  use_tensorboard: false
  use_wandb: false
training:
  adaptive_grad_clip_threshold: 0.01  # ✅ LHC FIX: ULTRA agresywne clipping (0.1 za słabe)
  alpha_classification: 1.0
  batch_size: 1  # ✅ LHC FIX: Powrót do 1 dla memory safety
  beta_contrastive: 1.0
  bridge_grad_clip_multiplier: 0.5  # ✅ LHC FIX: Conservative bridge clipping
  compute_detailed_metrics: true
  cpc_aux_weight: 0.02
  cpc_grad_clip_multiplier: 0.1  # ✅ LHC FIX: ULTRA conservative CPC clipping
  cpc_joint_weight: 0.2
  cpc_loss_type: gw_twins_inspired  # ✅ GW TWINS: Optimized for ultra-weak signals
  cpc_loss_weight: 1.0
  cpc_prediction_steps: 4
  cpc_temperature: 0.2
  dropout_rate: 0.15
  early_stopping_patience: 10
  eval_batch_size: 16
  eval_every_n_epochs: 1
  gamma_reconstruction: 0.15  # ✅ LHC FIX: Aktywuje SNN-AE decoder
  global_grad_clip_norm: 0.5
  gradient_accumulation_steps: 4
  gradient_clip_norm: 1.0
  gw_twins_redundancy_weight: 0.1
  keep_last_n_checkpoints: 3
  label_smoothing: 0.1
  learning_rate: 0.0001  # ✅ LHC FIX: Conservative LR dla CPC stability (0.001 za wysokie)
  max_memory_fraction: 0.2  # ✅ LHC FIX: ULTRA conservative memory (0.4 za dużo)
  num_epochs: 30
  optimizer: adamw
  per_module_grad_clip: true
  recon_loss_weight: 0.0
  
  # ✅ LHC SNN-AE: Aktywacja reconstruction loss
  gamma_reconstruction: 0.15  # Aktywuje SNN-AE decoder (było 0.0)
  save_best_model: true
  save_every_n_epochs: 5
  scheduler: cosine
  snn_grad_clip_multiplier: 1.0
  snn_loss_weight: 1.0
  stages:
    cpc_pretrain:
      epochs: 50
      freeze_encoder: false
      learning_rate: 0.001
    joint_training:
      epochs: 20
      freeze_none: true
      learning_rate: 0.0001
    snn_training:
      epochs: 30
      freeze_cpc: false
      learning_rate: 0.0005
  use_gradient_checkpointing: false
  warmup_epochs: 5
  weight_decay: 0.0001
