# Enhanced W&B Configuration for Neuromorphic GW Detection
# Complete configuration with comprehensive logging and monitoring

# Dataset configuration
data:
  # GWOSC data settings
  gwosc:
    events: ["GW150914", "GW151226", "GW170104"]  # Real events for training
    detectors: ["H1", "L1"]  # LIGO Hanford and Livingston
    sample_rate: 4096  # Hz
    duration: 4.0  # seconds
    
  # Synthetic data generation
  synthetic:
    noise_level: 0.1
    signal_strength_range: [0.1, 2.0]
    frequency_range: [20, 500]  # Hz
    
  # Data pipeline
  preprocessing:
    whitening: true
    bandpass_filter: [20, 500]
    downsampling_factor: 4
    
  # Training splits
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  batch_size: 32

# Model architecture
model:
  # CPC Encoder configuration
  cpc:
    encoder_dim: 512
    context_length: 256
    prediction_steps: 12
    temperature: 0.1
    downsample_factor: 4
    
  # Spike Bridge configuration  
  spike_bridge:
    encoding_strategy: "temporal_contrast"
    learnable_threshold: true
    learnable_scale: true
    initial_threshold: 1.0
    initial_scale: 1.0
    surrogate_slope: 4.0
    
  # SNN Classifier configuration
  snn:
    hidden_sizes: [256, 128, 64]
    num_classes: 2  # Detection vs. no detection
    surrogate_slope: 4.0
    tau_mem: 20.0  # ms
    tau_syn: 5.0   # ms
    spike_threshold: 1.0

# Training configuration
training:
  # Basic training settings
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 1e-5
  gradient_clip_norm: 1.0
  
  # Optimization
  optimizer: "adamw"
  scheduler: "cosine_warmup"
  warmup_epochs: 10
  
  # Performance targets
  target_accuracy: 0.95
  target_latency_ms: 100  # Sub-100ms inference
  
  # Early stopping
  early_stopping_patience: 10
  early_stopping_metric: "val_accuracy"
  
  # Validation frequency
  val_frequency: 5  # every 5 epochs
  checkpoint_frequency: 10  # every 10 epochs

# 🚀 Enhanced W&B Configuration
wandb:
  # Basic W&B settings
  enabled: true
  project: "neuromorphic-gw-detection-v2"
  entity: null  # Set your W&B username/team here
  name: null    # Auto-generated if null
  notes: "Enhanced neuromorphic gravitational wave detection with comprehensive monitoring"
  tags:
    - "neuromorphic"
    - "gravitational-waves" 
    - "snn"
    - "cpc"
    - "jax"
    - "enhanced-logging"
    
  # Logging frequency
  log_frequency: 10                    # Log metrics every 10 steps
  save_frequency: 100                  # Save artifacts every 100 steps
  log_model_frequency: 500             # Log model parameters every 500 steps
  
  # Feature toggles - Enable comprehensive tracking
  enable_hardware_monitoring: true     # CPU/GPU/memory monitoring
  enable_visualizations: true          # Custom plots and charts
  enable_alerts: true                 # Performance alerts
  enable_gradients: true              # Gradient tracking
  enable_model_artifacts: true        # Model saving
  enable_spike_tracking: true         # Neuromorphic spike patterns
  enable_performance_profiling: true  # Detailed performance metrics
  
  # Advanced W&B features
  watch_model: "all"                  # Track "gradients", "parameters", "all", or null
  log_graph: true                     # Log computation graph
  log_code: true                      # Log source code
  save_code: true                     # Save code artifacts
  
  # Custom metrics configuration - Neuromorphic-specific tracking
  neuromorphic_metrics: true          # Spike rates, encoding efficiency
  contrastive_metrics: true           # CPC-specific metrics
  detection_metrics: true             # GW detection accuracy metrics
  latency_metrics: true              # <100ms inference tracking
  memory_metrics: true               # Memory usage tracking
  
  # Dashboard and reporting
  create_summary_dashboard: true      # Auto-create summary plots
  dashboard_update_frequency: 100     # Update dashboard every 100 steps
  
  # Output and backup
  output_dir: "wandb_outputs"
  local_backup: true                  # Backup logs locally

# Hardware and performance optimization
platform:
  device: "auto"  # "cpu", "gpu", "metal", or "auto"
  precision: "float32"
  
  # JAX compilation settings
  jit_enable: true
  jit_cache: true
  
  # Memory management
  memory_fraction: 0.8
  preallocate_memory: false
  
  # Optimization flags
  xla_flags:
    - "--xla_force_host_platform_device_count=1"

# Professional logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File logging
  log_file: "logs/neuromorphic_gw_training.log"
  max_file_size_mb: 100
  backup_count: 5
  
  # W&B integration
  wandb_project: "neuromorphic-gw-detection-v2"
  
  # TensorBoard (fallback)
  tensorboard_dir: "tensorboard_logs"
  
# Experiment metadata
experiment:
  name: "enhanced-neuromorphic-gw-v2"
  description: "Enhanced neuromorphic gravitational wave detection with comprehensive W&B logging"
  version: "2.0.0"
  
  # Scientific objectives
  objectives:
    - "Achieve >95% detection accuracy"
    - "Maintain <100ms inference latency"
    - "Demonstrate energy-efficient neuromorphic processing"
    - "Comprehensive spike pattern analysis"
    - "Real-time performance monitoring"
  
  # Expected outcomes
  expected_results:
    accuracy_range: [0.90, 0.98]
    latency_range: [50, 100]  # ms
    memory_usage_mb: [1000, 4000]
    spike_rate_range: [10, 50]  # Hz
    energy_efficiency: "10x improvement over classical methods" 