# H100 Optimized Configuration
# Extends default.yaml with H100-specific optimizations
# Use: python cli.py train --config configs/h100_optimized.yaml

# =============================================================================
# H100 SPECIFIC OPTIMIZATIONS
# =============================================================================

system:
  # H100 has 80GB HBM3 - use more memory
  memory_fraction: 0.95  # vs 0.8 default
  use_mixed_precision: true  # H100 has excellent FP16/BF16 performance
  
  # Enable H100 specific features
  device: "gpu"  # explicit GPU
  jax_flags:
    - "--xla_gpu_enable_triton_softmax_fusion=true"
    - "--xla_gpu_triton_gemm_any=true"
    - "--xla_gpu_enable_async_collectives=true"

training:
  # H100 can handle MUCH larger batches
  batch_size: 32  # vs 1 default - 32x speedup!
  eval_batch_size: 64  # vs 16 default
  
  # Reduce gradient accumulation since we have larger batch
  gradient_accumulation_steps: 1  # vs 4 default
  
  # H100 has fast memory - can use gradient checkpointing efficiently
  use_gradient_checkpointing: true  # saves memory for even larger batches
  
  # Increase learning rate with larger batch (linear scaling rule)
  learning_rate: 0.0016  # 32x batch → 32x LR (0.00005 * 32)
  
  # H100 handles larger models well
  model_scaling: 1.5  # scale model dimensions by 1.5x

model:
  # Scale up model for H100
  cpc:
    latent_dim: 384  # vs 256 (1.5x)
    hidden_dim: 768  # vs 512 (1.5x)
    num_layers: 4  # vs 3 (more depth)
    
  snn:
    hidden_sizes: [384, 192, 96]  # vs [256, 128, 64] (1.5x)
    time_steps: 32  # vs 16 (more temporal resolution)

inference:
  # H100 can handle larger inference batches
  batch_size: 128  # vs 32 default
  
profiling:
  # Enable profiling to track H100 utilization
  enabled: true
  track_memory: true
  track_gpu_utilization: true
  
  # H100 specific benchmarks
  batch_sizes: [32, 64, 128, 256]  # much larger batches
  target_inference_ms: 10  # vs 100ms - H100 is FAST

# =============================================================================
# PERFORMANCE TIPS FOR H100
# =============================================================================
# 1. Batch Size: H100 excels with large batches (32-256)
# 2. Mixed Precision: Use BF16 for stability + speed
# 3. Memory: 80GB HBM3 - don't be afraid to use it!
# 4. Tensor Cores: Automatically used with mixed precision
# 5. Multi-Instance GPU (MIG): Can partition if needed

# Expected speedup vs default config:
# - Training: 30-50x faster (batch 32 vs 1, plus H100 speed)
# - Inference: 100x faster (batch 128, optimized kernels)
# - Memory usage: ~40GB (plenty of headroom on 80GB H100)
